name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update -qq
        sudo apt-get install -y tcl8.6-dev
        sudo apt-get install -y libzookeeper-mt-dev libzookeeper-mt2
    - name: configure
      run: |
        autoreconf -vi
        ./configure
    - name: make
      run: make
    - name: install
      run: sudo make install